name: Quantik Golang Build

on:
  workflow_call:
    inputs:
      working-directory:
        required: false
        type: string
        default: "./"

      go-vet:
        required: false
        type: boolean
        default: true

      go-test:
        required: false
        type: boolean
        default: true


      git-auth-user:
        required: false
        type: string
        description: 'The user the PAT below belongs to'
    secrets:
      git-auth-token:
        required: false
        description: 'The PAT for accessing private repos'


jobs:
  build-and-test:
    name: Builds and tests Golang project
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          cache: true
        # just use latest for now
        #   go-version: 1.19
      - name: Configure git for private modules
        if: ${{ env.TOKEN }} && ${{ env.USER }}
        env:
          TOKEN: ${{ secrets.git-auth-token }}
          USER: ${{ secrets.git-auth-user }}
        run: git config --global url."https://${USER}:${TOKEN}@github.com".insteadOf "https://github.com"

      - name: Vet
        if: ${{ inputs.go-vet  }} == 'true'
        env:
          DO_VET: ${{ inputs.go-vet }}
          GOPRIVATE: github.com/quantik-no/*
        run: go vet -v ./...

      - name: Test
        if: ${{ inputs.go-test }} == 'true'
        env:
          DO_TEST: ${{ inputs.go-test }}
          GOPRIVATE: github.com/quantik-no/*
        run: go test -v ./...

      - name: Build
        env:
          GOPRIVATE: github.com/quantik-no/*
        run: go build -v ./...
