name: Quantik .NET Build

on:
  workflow_call:
    secrets:
      nuget-auth-token:
        required: false
        description: 'The PAT for accessing the nuget local repo'
    inputs:
      working-directory:
        required: false
        default: "."
        type: string
      testing-directory:
        required: false
        default: "."
        type: string
      tests-verbosity:
        required: false
        type: string
        default: normal


      nuget-source-url:
        required: false
        type: string
        default: https://nuget.pkg.github.com/quantik-no/index.json
      dotnet-version:
        required: false
        type: string
        default: '6.0.x'
      dotnet-configuration:
        required: false
        type: string
        default: 'Release'
jobs:
  build-and-test:
    name: Builds and tests .NET
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: '${{ inputs.working-directory }}'
    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: ${{ inputs.dotnet-version }}
        source-url: ${{ inputs.nuget-source-url }}
      env:
          NUGET_AUTH_TOKEN: ${{ secrets.nuget-auth-token }}
    - name: Install dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --configuration ${{ inputs.dotnet-configuration }} --no-restore
    - name: Test
      working-directory: '${{ inputs.testing-directory }}'
      run: dotnet test --verbosity=${{ inputs.tests-verbosity }}
